#!/bin/bash
#
# $ cat /usr/bin/emacsdaemon 
# #!/usr/bin/emacs --daemon
#
. /etc/rc.conf
. /etc/rc.d/functions

USER="michael"

PID=$(pgrep emacsdaemon)

case "$1" in
 start)
   stat_busy "Starting Emacs Daemon"
   [ -z "$PID" ] && su $USER -c /usr/bin/emacsdaemon &>/dev/null
   if [ $? = 0 ]; then
     add_daemon emacsd
     stat_done
   else
     stat_fail
     exit 1
   fi
   ;;
 stop)
   stat_busy "Stopping Emacs Daemon"
   [ -n "$PID" ] && su $USER -c "/usr/bin/emacsclient --eval '(kill-emacs)'" &>/dev/null
   if [ $? = 0 ]; then
     rm_daemon emacsd
     stat_done
   else
     stat_fail
     exit 1
   fi
   ;;
 restart)
   $0 stop
   sleep 1
   $0 start
   ;;
 *)
   echo "usage: $0 {start|stop|restart}"  
esac
