#!/bin/bash
# Скрипт для vpn соединения через network manager
# Ждет, пока кабель будет подключен
# Автоматический реконект при нерабочей сети/интернете

# Имена интерфейсов
PPP="ppp0"
ETH="eth0"
# UUID подключения по проводной сети
ETH_UUID="73ea227c-25d4-4b08-93ac-f2ccdab5d870"
# UUID подключения по VPN
VPN_UUID="38be0e58-00b0-448b-8440-040d64f44730"
# Адрес для проверки сети
ETHPING="172.16.254.254"
# Адрес для проверки интернета
PPPPING="google.com"

NMCLI="ck-launch-session nmcli"

function Main
{
    if EthAvailable; then
	echo Кабель подключен.
	if [ "$($NMCLI -t -f uuid con status)" ]; then
	    echo Есть активные соединения.
	    if [ "$($NMCLI con status| grep $ETH_UUID)" ]; then
		echo ETH подключен.
		if NetUp; then
		    echo Сеть работает.
		    if [ "$($NMCLI con status |grep $VPN_UUID)" ]; then
			echo VPN работает.
			until InetUp; do
			    sleep 1s
			done
			echo Интернет упал, отключаю VPN.
			$NMCLI con down uuid $VPN_UUID >/dev/null 2>&1			
			echo Интернет упал, отключаю ETH.
			$NMCLI con down uuid $ETH_UUID >/dev/null 2>&1			
		    else
			echo VPN не работает, поднимаю VPN.
			$NMCLI con up uuid $VPN_UUID >/dev/null 2>&1
			sleep 10s
		    fi
		else
		    echo Сеть не работает, отключаю ETH.
	    	    $NMCLI con down uuid $ETH_UUID >/dev/null 2>&1
		fi
	    else
		echo Активно не-ETH соединение.
		sleep 10s
	    fi
	else
	    echo Нет активных соединений. Поднимаю ETH.
    	    $NMCLI con up uuid $ETH_UUID >/dev/null 2>&1
	    sleep 1s
	fi
    else
	sleep 1s
    fi
}

function EthAvailable
{
    case "$($NMCLI -t -f device,state dev |grep $ETH)" in
	"$ETH:отключено")
	    return 0
	    ;;
	"$ETH:подключено")
	    return 0
	    ;;
	*)
	    return 1
	    ;;
    esac
}

function NetUp
{
    ping -I $ETH -c 3 $ETHPING >/dev/null 2>&1
    if [ $? == "0" ]; then
	return 0
    else
	return 1
    fi
}

function InetUp
{
    ping -I $PPP -c 10 $PPPPING >/dev/null 2>&1
    if [ $? == "0" ]; then
	return 0
    else
	return 1
    fi
}

while [ 1 ]; do
    Main
    sleep 1s
done
