#!/bin/bash
# Скрипт для vpn соединения через network manager
# Ждет, пока кабель будет отключен
# Автоматический реконект при нерабочей сети/интернете

# Имена интерфейсов
PPP="ppp0"
ETH="eth0"
# UUID подключения по проводной сети
ETH_UUID="73ea227c-25d4-4b08-93ac-f2ccdab5d870"
# UUID подключения по VPN
VPN_UUID="38be0e58-00b0-448b-8440-040d64f44730"

function Main
{
    # Если подключен кабель
    if EthAvailable; then
	echo кабель подключен
	# Если есть соединения
	if [ "$(nmcli -t -f uuid con status)" ]; then
	    echo есть соединения
	    # Если Среди них есть ETH
	    if [ "$(nmcli con status| grep $ETH_UUID)" ]; then
		echo среди них есть ETH
		# Если сеть работает
		if NetUp; then
		    echo сеть работает
		    # Если VPN подключен
		    if [ "$(nmcli con status |grep $VPN_UUID)" ]; then
			echo VPN подключен
			# Пока интернет работает
			until InetUp; do
			    echo интернет работает
			    sleep 1s
			done
		    else
			echo VPN не подключен -- подключаем
		        # Если VPN не подключен -- подключаем
			nmcli con up uuid $VPN_UUID
			sleep 10s
		    fi
		else
		    echo Сеть не работает -- отключаем
	            # Если сеть не работает -- отключаем сеть
	    	    nmcli con down uuid $ETH_UUID
		fi
	    else
		echo Среди сетей нет ETH -- ничего не делаем, т.к. подключена другая сеть
                # Если среди них нет ETH, то ничего не делаем (подключена другая сеть)
		sleep 10s
	    fi
	else
	    echo Подключаем ETH
            # Если нет соединений, то подключаем ETH
    	    nmcli con up uuid $ETH_UUID
	    sleep 1s
	fi
    else
	echo Кабель не подключен
        # Если кабель не подключен, то ждем	
	sleep 1s
    fi
}

function EthAvailable
{
    case "$(nmcli -t -f device,state dev |grep $ETH)" in
	"$ETH:отключено")
	    echo return 0 in EthAvailable
	    return 0
	    ;;
	"$ETH:подключено")
	    echo return 0 in EthAvailable
	    return 0
	    ;;
	*)
	    echo return 1 in EthAvailable
	    return 1
	    ;;
    esac
}

function NetUp
{
    ping -I $ETH -c 3 google.com >/dev/null 2>&1
    if [ $? == "0" ]; then
	return 1
    else
	return 0
    fi
}

function InetUp
{
    ping -I $PPP -c 10 google.com >/dev/null 2>&1
    if [ $? == "0" ]; then
	return 1
    else
	return 0
    fi
}

while [ 1 ]; do
    Main
done
