#!/bin/bash
# Скрипт для vpn соединения через network manager
# Ждет, пока кабель будет подключен
# Автоматический реконект при нерабочей сети/интернете

# Имена интерфейсов
PPP="ppp0"
ETH="eth0"
# UUID подключения по проводной сети
ETH_UUID="73ea227c-25d4-4b08-93ac-f2ccdab5d870"
# UUID подключения по VPN
VPN_UUID="38be0e58-00b0-448b-8440-040d64f44730"
# Адрес для проверки сети
ETHPING="172.16.254.254"
# Адрес для проверки интернета
PPPPING="google.com"
# Команда для вывода даты
DATE="date +%d.%m.%y-%R"

NMCLI="ck-launch-session nmcli"


function Main
{
    if EthAvailable; then
#	echo $($DATE) Кабель подключен.
	if [ "$($NMCLI -t -f uuid con status)" ]; then
#	    echo $($DATE) Есть активные соединения.
	    if [ "$($NMCLI con status| grep $ETH_UUID)" ]; then
#		echo $($DATE) ETH подключен.
		if NetUp; then
#		    echo $($DATE) Сеть работает.
		    if [ "$($NMCLI con status |grep $VPN_UUID)" ]; then
#			echo $($DATE) VPN работает.
#			if ! InetDown; then
#			    echo $($DATE) Интернет работает.
#			fi
			until InetDown; do
			    sleep 1s
			done
#			echo $($DATE) Интернет упал, отключаю VPN.
			$NMCLI con down uuid $VPN_UUID >/dev/null 2>&1			
#			echo $($DATE) Интернет упал, отключаю ETH.
			$NMCLI con down uuid $ETH_UUID >/dev/null 2>&1			
		    else
#			echo $($DATE) VPN не работает, поднимаю VPN.
			$NMCLI con up uuid $VPN_UUID >/dev/null 2>&1
			sleep 10s
		    fi
		else
#		    echo $($DATE) Сеть не работает, отключаю ETH.
	    	    $NMCLI con down uuid $ETH_UUID >/dev/null 2>&1
		fi
	    else
#		echo $($DATE) Активно не-ETH соединение.
		sleep 10s
	    fi
	else
#	    echo $($DATE) Нет активных соединений. Поднимаю ETH.
    	    $NMCLI con up uuid $ETH_UUID >/dev/null 2>&1
	    sleep 5s
	fi
    else
	sleep 1s
    fi
}

function EthAvailable
{
    case "$($NMCLI -t -f device,state dev |grep $ETH)" in
	"$ETH:отключено")
	    return 0
	    ;;
	"$ETH:подключено")
	    return 0
	    ;;
	*)
	    return 1
	    ;;
    esac
}

function NetUp
{
    ping -I $ETH -c 2 -w 10 $ETHPING >/dev/null 2>&1
    if [ $? == "0" ]; then
	return 0
    else
	return 1
    fi
}

function InetDown
{
    ping -I $PPP -c 2 -w 10 $PPPPING >/dev/null 2>&1
    if [ $? == "0" ]; then
	return 1
    else
	return 0
    fi
}

while [ 1 ]; do
    Main
    sleep 1s
done
