#!/bin/bash
#
# Managing volume and send notify.
# Copyright (C) 2012 Mikhail Klementyev aka jollheef <jollheef@riseup.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

Action=$1
Quantity=$2
NotifyExpireTime=500

function Main 
{
    TestRun
    case $Action in
        inc)
            PlusOrMinus="+"
            ChangeVolume
            SendNotify
            ;;
        dec)
            PlusOrMinus="-"
            ChangeVolume
            SendNotify
            ;;
        set)
            amixer sset 'Master' $Quantity% >/dev/null
            ;;
        toggle)
            if [[ ''$(amixer sset 'Master' toggle | grep "Mono:" | awk '{print $6}')'' == '[off]' ]] 
            then
                notif="Volume::off"
            else
                notif="Volume::on"
            fi
            SendNotify
            ;;
        show)
            notif=$(amixer sget Master |grep "Mono:" |awk '{print $4}' | sed 's/\[//;s/\]//')            
            echo $notif
            ;;
        *)
            echo "Use: volume [inc,dec,set,toggle,show] [0-100]"
            ;;
    esac
}

function ChangeVolume
{
    notif="Volume::$(amixer sset Master $Quantity%$PlusOrMinus |grep "Mono:" |awk '{print $4}' |sed 's/\[//;s/\]//')" 
}

function SendNotify
{
    notify-send -t $NotifyExpireTime "$notif" 
}

function TestRun
{
    PID=`pgrep volume`
    if [[ -z $PID ]]; then
        exit 1;
    fi
}

Main
